# middle LED stays on when connected to central (10hr "blink" = effectively permanent)
CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=2
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=0
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=0
CONFIG_RGBLED_WIDGET_CONN_BLINK_MS=36000000
