# LED0 always on regardless of connection state (power indicator)
CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=1
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=1
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=1
CONFIG_RGBLED_WIDGET_CONN_BLINK_MS=36000000
