CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_POINTING=y

CONFIG_RGBLED_WIDGET=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_BT_BAS=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

# battery colors: 3 LEDs = high, 2 = medium, 1 = low
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_HIGH=7
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MEDIUM=3
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_LOW=1

# layer colors
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=1
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=4
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=2
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=3
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=5
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=6
